<a href="https://colab.research.google.com/github/sturu1/FRI/blob/master/2020_08_07_%EC%98%A4%ED%9B%84%EC%88%98%EC%97%85.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[2.7764e-35, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 6.1657e-44],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 0.0000e+00]])


In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.2702, 0.3512, 0.2677],
        [0.7924, 0.2843, 0.9383],
        [0.0909, 0.4233, 0.8465],
        [0.4036, 0.5603, 0.1945],
        [0.3768, 0.7543, 0.4255]])


In [8]:
x = torch.zeros(5, 3, dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [9]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [10]:
x = x.new_ones(5, 3, dtype = torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [11]:
x= torch.rand_like(x, dtype = torch.float)
print(x)

tensor([[0.4791, 0.6035, 0.5003],
        [0.0236, 0.5065, 0.7618],
        [0.7898, 0.0070, 0.4012],
        [0.1055, 0.3057, 0.4614],
        [0.0801, 0.6672, 0.4702]])


In [12]:
print(x.size())

torch.Size([5, 3])


In [13]:
y = torch.rand(5, 3)
print(x)

tensor([[0.4791, 0.6035, 0.5003],
        [0.0236, 0.5065, 0.7618],
        [0.7898, 0.0070, 0.4012],
        [0.1055, 0.3057, 0.4614],
        [0.0801, 0.6672, 0.4702]])


In [14]:
print(torch.add(x, y))

tensor([[0.7146, 1.1136, 0.7923],
        [0.8273, 0.5805, 1.3282],
        [1.2667, 0.0804, 0.7107],
        [0.7625, 1.1213, 1.0321],
        [0.7709, 1.4658, 1.4341]])


In [16]:
result = torch.empty(5, 3)
torch.add(x, y, out = result)
print(result)

tensor([[0.7146, 1.1136, 0.7923],
        [0.8273, 0.5805, 1.3282],
        [1.2667, 0.0804, 0.7107],
        [0.7625, 1.1213, 1.0321],
        [0.7709, 1.4658, 1.4341]])


In [18]:
y.add(x)
print(y)

tensor([[0.2355, 0.5102, 0.2920],
        [0.8037, 0.0740, 0.5664],
        [0.4768, 0.0734, 0.3095],
        [0.6570, 0.8155, 0.5707],
        [0.6908, 0.7986, 0.9639]])


In [19]:
print(x[:, 1])

tensor([0.6035, 0.5065, 0.0070, 0.3057, 0.6672])


In [21]:
x = torch.randn(4, 4)
print(x)
y = x.view(16)
print(y)

tensor([[-1.1246,  3.0267, -0.2126, -0.1227],
        [ 1.0921, -0.4286, -1.6811,  0.6656],
        [ 0.2184,  0.6263, -0.5869, -0.6360],
        [ 1.7618,  0.1955,  1.3523, -0.4984]])
tensor([-1.1246,  3.0267, -0.2126, -0.1227,  1.0921, -0.4286, -1.6811,  0.6656,
         0.2184,  0.6263, -0.5869, -0.6360,  1.7618,  0.1955,  1.3523, -0.4984])


In [23]:
z = x.view(-1, 8)
print(z)

tensor([[-1.1246,  3.0267, -0.2126, -0.1227,  1.0921, -0.4286, -1.6811,  0.6656],
        [ 0.2184,  0.6263, -0.5869, -0.6360,  1.7618,  0.1955,  1.3523, -0.4984]])


In [24]:
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [26]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.4507])
-1.4507375955581665
